# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  VERSION: 0.6-SNAPSHOT

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION  }}.${{ github.run_number }}
        release_name: RemoveItems-${{ env.VERSION }}.${{ github.run_number }}
        body: |
          Changes in this release
          - First change
          - Second change
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: target/RemoveItems-${{ env.VERSION }}.jar
        asset_name: RemoveItems-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive
    - name: Upload to Artifactory
      id: upload-to-artifactory
        #uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
      run: jfrog rt u RemoveItems-${{ env.VERSION }}.jar https://steve4744.jfrog.io/artifactory/steve4744-repo/
